/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Collator;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import registro_ciclistas_rutas.Conexion;

/**
 *
 * @author Sergio Jaramillo
 */
public class Tabla_rutas extends javax.swing.JDialog {
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel model;
    

    /**
     * Creates new form Tabla_rutas
     */
    public Tabla_rutas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        show_rutas();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_lugInicio = new javax.swing.JTextField();
        txt_lugFinal = new javax.swing.JTextField();
        txt_km = new javax.swing.JTextField();
        txt_horaInicio = new javax.swing.JTextField();
        txt_horaFinal = new javax.swing.JTextField();
        txt_dia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rutas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Registro de rutas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Lugar inicio:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Lugar final:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Hora inicio:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Hora final:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("KM recorridos: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Dia:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_lugInicio)
                    .addComponent(txt_lugFinal)
                    .addComponent(txt_km, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_horaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txt_lugInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txt_lugFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_horaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btn_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_add.setText("Agregar");
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_edit.setText("Editar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addGap(164, 164, 164)
                .addComponent(btn_eliminar)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_edit)
                    .addComponent(btn_eliminar))
                .addGap(35, 35, 35))
        );

        tbl_rutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "lugar inicio", "lugar final", "Hora inicio", "Hora final", "KM", "tiempo", "fecha"
            }
        ));
        tbl_rutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_rutasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_rutas);
        if (tbl_rutas.getColumnModel().getColumnCount() > 0) {
            tbl_rutas.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
        agregarRuta();
    }//GEN-LAST:event_btn_addMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        editarRuta();
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_rutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_rutasMouseClicked
        int row = tbl_rutas.getSelectedRow();
        System.out.println(row);
        if(row>=0){
            String id = tbl_rutas.getValueAt(row, 0).toString();
            String li = tbl_rutas.getValueAt(row, 1).toString();
            String lf = tbl_rutas.getValueAt(row, 2).toString();
            String hi = tbl_rutas.getValueAt(row, 3).toString();
            String hf = tbl_rutas.getValueAt(row, 4).toString();
            String km = tbl_rutas.getValueAt(row, 5).toString();
            String tiempo = tbl_rutas.getValueAt(row, 6).toString();
            
            String fecha = tbl_rutas.getValueAt(row, 7).toString();
            System.out.println(li+" - "+ lf+" - "+hi+" - "+hf+" - "+km+" - "+tiempo+" - "+fecha);
            
            txt_dia.setText(""+ fecha);
            txt_horaFinal.setText(hf);
            txt_horaInicio.setText(hi);
            txt_km.setText(""+ km);
            txt_lugFinal.setText(lf);
            txt_lugInicio.setText(li);
            
        }
    }//GEN-LAST:event_tbl_rutasMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        eliminarRuta();
    }//GEN-LAST:event_btn_eliminarMouseClicked


    public void agregarRuta(){
        
        String lugarInicio=txt_lugInicio.getText();
        String lugFinal=txt_lugFinal.getText();
        String hi=txt_horaInicio.getText();
        String hf=txt_horaFinal.getText();
        float km=Float.valueOf(txt_km.getText());
        
        String dia= txt_dia.getText();
        
        
        if(Integer.parseInt(dia)>30 || Integer.parseInt(dia)<0){
            JOptionPane.showMessageDialog(this, "por favor ingrese una fecha que funcione");
        }else{
        int tiempo=0;
            int tiempo1=Integer.parseInt(hi);
            int tiempo2=Integer.parseInt(hf);
            if(tiempo1>24 || tiempo2>24 || tiempo1<0 || tiempo2<0){
                JOptionPane.showMessageDialog(this, "ingrese horas que coincidan");
            }else{
                tiempo= obtenerTiempo(tiempo1, tiempo2);
            }
        if (lugFinal.isEmpty() || lugarInicio.isEmpty() || txt_km.getText().isEmpty() || hi.isEmpty()|| hf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
        } else {
            
            System.out.println(tiempo);
            System.out.println(lugarInicio+" "+ lugFinal +" "+ hi +" "+ hf +" "+ km);
            String query = "INSERT INTO rutas(Lugar_inicio, Lugar_final, Hora_inicio, Hora_final ,KM , tiempo ,fecha ) VALUES('" + lugarInicio + "','" + lugFinal + "','" + hi + "','" + hf + "','" + km + "','" + tiempo + "','" + dia + "-09-2021')";
                    try {
                        cn = con.getConnection();
                        st = cn.createStatement();
                        st.executeUpdate(query);
                        JOptionPane.showMessageDialog(this, "Se ha creado el registro con éxito");
                        clear_rows_table();
                        show_rutas();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "No se pudo crear el registro");
                    
                    }            
        }
        } 
    }
    
    public void editarRuta(){
    int row = tbl_rutas.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
        }else{
            String li = txt_lugInicio.getText();
            String lf = txt_lugFinal.getText();
            String hi = txt_horaInicio.getText();
            String hf = txt_horaFinal.getText();
            float km = Float.valueOf(txt_km.getText());
            
            
            int tiempo1=Integer.parseInt(hi);
            int tiempo2=Integer.parseInt(hf);
            int tiempo= obtenerTiempo(tiempo1,tiempo2);
            
              if (li.equals("") || lf.equals("")) {
                    JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
              }else{
                  String id= tbl_rutas.getValueAt(row, 0).toString();
                  System.out.println("el id es: "+id);
                  String sql = "UPDATE rutas SET `Lugar_inicio` = '"+li+"', `Lugar_final`= '"+lf +"', `Hora_inicio`= '"+hi +"', `Hora_final`= '"+hf +"', `KM`= '"+km +"', `tiempo`= '"+tiempo +"' WHERE `id` = '"+id+"'";
                    try{
                      cn = con.getConnection();
                      st = cn.createStatement();
                      st.executeUpdate(sql);
                      clear_rows_table();
                      JOptionPane.showMessageDialog(this, "Se ha actualizado el registro");
                      show_rutas();
                  }catch(SQLException e){
                      JOptionPane.showMessageDialog(this, e);
                  }
             }       
        }
    }
    void eliminarRuta(){
        int row = tbl_rutas.getSelectedRow();
        System.out.println("fila: "+ row);
        if(row == -1)
            JOptionPane.showMessageDialog(this, "Debes de seleccionar un registro de la tabla");
        else{
            String id= tbl_rutas.getValueAt(row, 0).toString();
            
            String sql = "DELETE FROM `rutas` WHERE id = "+id;
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                clear_rows_table();
                JOptionPane.showMessageDialog(this, "Se ha eliminado el registro");
                show_rutas();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la información del registro");
            }
        }
    }
    
    
    void show_rutas(){
        String query = "SELECT * FROM rutas";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(query);
            Object[] ruta = new Object[8];
            model = (DefaultTableModel)tbl_rutas.getModel();
            while(rs.next()){
                
                ruta[0] = rs.getString("id");
                ruta[1] = rs.getString("Lugar_inicio");
                ruta[2] = rs.getString("Lugar_final");
                ruta[3] = rs.getString("Hora_inicio");
                ruta[4] = rs.getString("Hora_final");
                ruta[5] = rs.getFloat("KM");
                ruta[6] = rs.getInt("tiempo");
                ruta[7] = rs.getString("fecha");
                
                
                model.addRow(ruta);
            }
            tbl_rutas.setModel(model);
        }catch(SQLException e){
            JOptionPane.showConfirmDialog(this, "error al mostrar la tabla");
        }
    }
    
    void clear_rows_table(){
        for (int i = 0; i < tbl_rutas.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
        txt_dia.setText("");
        txt_horaFinal.setText("");
        txt_horaInicio.setText("");
        txt_km.setText("");
        txt_lugFinal.setText("");
        txt_lugInicio.setText("");
    }
    
    public int obtenerTiempo(int t1, int t2){
        int t=0;
        if(t1>t2){
            if(t1>12){
                t1=t1-12;
            }
            t=t1+t2;
        }else{
            t=t2-t1;
        }
        
        
        return t;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_rutas;
    private javax.swing.JTextField txt_dia;
    private javax.swing.JTextField txt_horaFinal;
    private javax.swing.JTextField txt_horaInicio;
    private javax.swing.JTextField txt_km;
    private javax.swing.JTextField txt_lugFinal;
    private javax.swing.JTextField txt_lugInicio;
    // End of variables declaration//GEN-END:variables
}
